name: DAST-Vercel

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  actions: write  # ← allow creating artifact containers

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: No operation
        run: echo "DAST-Vercel workflow triggered, but no action defined."